name: Continuous Test Integration for Simulated data

on:
  push:
    branches: [sim_data]
  pull_request:
    branches: [sim_data]

jobs:
  run_style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: simulate_data/env.yml
      - run: |
          python -m pip install --upgrade pip
          python -m pip install pycodestyle
          pycodestyle $(git ls-files "simulate_data/*.py")
          pycodestyle $(git ls-files "simulate_data/tests/*.py")
  run_code_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: env.yml
      - run: |
          python -m pip install --upgrade pip
          python -m pip install numpy
          conda install numpy
          ./simulate_data/run_tests.sh
