name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cgrs
          environment-file:survey_analysis/environment.yml
      - run: bash survey_analysis/tests/test_probability.sh
  code_style:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cgrs
          environment-file: survey_analysis/environment.yml
      - run: pycodestyle $(git ls-files "*.py")

  unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cgrs
          environment-file: survey_analysis/environment.yml
      - run: python -m unittest survey_analysis/tests/test_utils.py
